### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by sladeXD** [legoraft/simple-armor-hud#13] opened 2022-10-26 09:23 UTC
i dont really know if this is a bug however my game crashes everytime i try to launch my game 
(i do have fabric api for my other mods to work)

**Comment by legoraft** [comment] 2022-10-28 06:05
check if simple armor hud is the cause of this, I also use the fabric api in my mod setup and it doesn't crash.

**Comment by legoraft** [comment] 2022-10-30 20:34
closing, because bug is not recreatable

**Closed by legoraft** 2022-10-30 20:34 UTC
Labels: bug
